<a href="https://colab.research.google.com/github/SAISHREE-19/AIML/blob/main/LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [ ]:
a1.shape

(4,)

In [ ]:
a1.size

4

In [ ]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.shape

(2, 4)

In [ ]:
a2.size

8

In [ ]:
a2.ndim

2

In [ ]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
a3.shape

(1, 3, 3)

In [ ]:
a3.size

9

In [ ]:
type(a3)

numpy.ndarray

In [ ]:
import numpy as np
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
z1.shape

(3,)

In [ ]:
z1.size

3

In [ ]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2.shape

(3, 4)

In [ ]:
z2.size

12

In [ ]:
z2.ndim

2

In [ ]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z3.ndim

3

In [ ]:
z3.shape

(2, 3, 4)

In [ ]:
z3.size

24

In [ ]:
import numpy as np
a1=np.ones(3)
a1

array([1., 1., 1.])

In [ ]:
a2=np.ones([3,4])
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a2=np.ones([3,4],dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
a2.shape

(3, 4)

In [ ]:
a2.size

12

In [ ]:
a3=np.ones([4,2,3])
a3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a3.shape

(4, 2, 3)

In [ ]:
a3.size

24

In [ ]:
z3.ndim

3

In [ ]:
f1=np.full(3,9)
f1

array([9, 9, 9])

In [ ]:
f1=np.full(3,9,dtype=float)
f1

array([9., 9., 9.])

In [ ]:
f1.shape

(3,)

In [ ]:
f1.size

3

In [ ]:
f2=np.full([2,3],9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
f3=np.full([4,2,3],10)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [ ]:
f3.shape

(4, 2, 3)

In [ ]:
f3.size

24

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])
add=np.add(a,b)
add

array([2, 4, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])
sub=np.subtract(a,b)
sub

array([0, 0, 0])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])
mul=np.multiply(a,b)
mul

array([1, 4, 9])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])
div=np.divide(a,b)
div

array([1., 1., 1.])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])
add=np.mod(a,b)
add

array([0, 0, 0])

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3])
add=np.power(a,b)
add

array([ 1,  4, 27])